[general]
import = [
    "~/.config/alacritty/themes/themes/omni.toml"
]

[window]
opacity = 0.9
padding = { x = 10, y = 10}

[font]
size = 13.0

[font.bold]
family = "DejaVuSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "DejaVuSansM Nerd Font"
style = "Italic"

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key= "V", mods= "Control", action= "Paste" },
   { key= "C", mods= "Control", action= "Copy" },
]

[cursor]
style = "Block"
blink_interval = 500  # Blink interval in milliseconds
blink_timeout = 100 # Timeout before blinking starts in milliseconds
